symlinks:
  # Reemplaza los ficheros existentes por enlaces simbolicos
  override: true

  # links simbolicos
  links:
    # kitty terminal
    - ~/.config/kitty/kitty.conf:~/dotfiles/share/config/kitty/kitty.conf

    # Neofetch
    - ~/.config/neofetch/config.conf:~/dotfiles/share/config/neofetch/config.conf

    # iTerm2
    - ~/.config/iterm2/com.googlecode.iterm2.plist:~/dotfiles/macOS/config/iterm2/com.googlecode.iterm2.plist

    # Window manager y atajos de teclado
    - ~/.config/yabai/yabairc:~/dotfiles/macOS/config/yabai/yabairc
    - ~/.config/skhd/skhdrc:~/dotfiles/macOS/config/skhd/skhdrc
