symlinks:
  # Reemplaza los ficheros existentes por enlaces simbolicos
  override: true

  # links simbolicos
  links:
    # kitty terminal
    - ~/.config/kitty/kitty.conf:~/dotfiles/macOS/config/kitty/kitty.conf

    # Neofetch
    - ~/.config/neofetch/config.conf:~/dotfiles/macOS/config/neofetch/config.conf

    # iTerm2
    - ~/.config/iterm2/com.googlecode.iterm2.plist:~/dotfiles/macOS/config/iterm2/com.googlecode.iterm2.plist

