#!/bin/bash

if [[ $XDG_CONFIG_HOME != "XFCE" ]]; then
    $HOME/.config/polybar/launch.sh --forest
fi

pgrep -x sxhkd > /dev/null || sxhkd &

pkill picom
picom --config "${HOME}/.config/picom/picom.conf" &

bspc monitor -d I II III IV

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config border_width        0
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#ffffff"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#5f667c"

xsetroot -cursor_name left_ptr &
