/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.magonxesp.dotfiles

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import io.github.magonxesp.dotfiles.commands.UpdateSymbolicLinksCommand
import io.github.magonxesp.dotfiles.commands.UpdateDotfilesCommand

class MainCommand : CliktCommand(
	name = "Dotfiles",
	help = "The cli program for manage dotfiles"
) {
	override fun run() {}
}

fun main(args: Array<String>) {
	MainCommand()
		.subcommands(
			UpdateSymbolicLinksCommand(),
			UpdateDotfilesCommand()
		)
		.main(args)
}
