symlinks:
  # Reemplaza los ficheros existentes por enlaces simbolicos
  override: true

  # links simbolicos
  links:
    # kitty terminal
    - ~/.config/kitty/kitty.conf:~/dotfiles/linux/config/kitty/kitty.conf

    # Neofetch
    - ~/.config/neofetch/config.conf:~/dotfiles/share/config/neofetch/config.conf

    # Rofi
    - ~/.config/rofi/config.rasi:~/dotfiles/linux/config/rofi/config.rasi
    - ~/.config/rofi/slate.rasi:~/dotfiles/linux/config/rofi/themes/slate.rasi

    # WM config
    - ~/.config/bspwm/bspwmrc:~/dotfiles/linux/config/bspwm/bspwmrc
    - ~/.config/sxhkd/sxhkdrc:~/dotfiles/linux/config/sxhkd/sxhkdrc
    - ~/.config/picom/picom.conf:~/dotfiles/linux/config/picom/picom.conf
    - ~/.config/gtk-3.0/gtk.css:~/dotfiles/linux/config/gtk-3.0/gtk.css
    - ~/.config/polybar:~/dotfiles/linux/config/polybar

    # Themes
    - ~/.themes:~/dotfiles/linux/themes
    - ~/.local/share/fonts:~/dotfiles/linux/fonts
